apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "inletsPro.fullname" . }}
  labels:
    {{- include "inletsPro.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "inletsPro.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "inletsPro.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "server"
            - "--auto-tls={{ .Values.autoTLS }}"
            {{- if ne .Values.commonName "" }}
            - "--common-name={{ .Values.commonName }}"
            {{- end }}
            - "--token-from=/etc/inlets/token"          
          ports:
            - name: control
              containerPort: 8123
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: temp-volume
              mountPath: /tmp            
            - name: token
              mountPath: "/etc/inlets"
              readOnly: true
      volumes:
      - name: temp-volume
        emptyDir: {}         
      - name: token
        secret:
          secretName: {{ template "inletsPro.secretName" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
